config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'toilets#index'
  get '/dashboard', to: 'pages#dashboard'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :toilets do
    resources :bookings, only: %i[new create]
    resources :reviews, only: %i[new create show index]
  end
  resources :bookings, only: %i[show destroy index edit update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :toilet
  belongs_to :user

  validates :start_date, presence: true
  attribute :status, default: true
  def end_date
    (:start_date + 15.minutes)
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :toilet

  validates :description, length: { maximum: 1000, too_long: "%{count} characters is the maximum allowed" }
  validates :rating, presence: true, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
end

app/models/toilet.rb
class Toilet < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_one_attached :photo

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  enum gender: {
    binary: 0,
    male: 1,
    female: 2,
    non_binary: 3
  }

  # validates :gender, presence: true, inclusion: { :in => ["male", "female", "non-binary"] }

  validates :category, presence: true, inclusion: { :in => ['urinal', 'washing toilet', 'Turkish toilet', 'dry toilet', 'chemical toilet'] }
  validates :price, presence: true
  validates :location, presence: true
  validates :name, presence: true
  validates :description, presence: true, length: { maximum: 250, too_long: "%{count} characters is the maximum allowed" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews
  has_many :bookings
  has_many :toilets
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_toilet, only: %i[new create]
  before_action :find_booking, only: %i[update edit]

  def index
    @bookings = Booking.all
  end

  def new
    @booking = Booking.new
  end

  def show
  end

  def edit
  end

  def update
    @booking.update(booking_params)
    redirect_to booking_path(@booking)
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.toilet = @toilet
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :status)
  end

  def set_toilet
    @toilet = Toilet.find(params[:toilet_id])
  end

  def find_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def dashboard
    @user = current_user
    @reviews = @user.reviews
    @bookings = @user.bookings
    @toilets = @user.toilets
    @new_booking = Booking.new
  end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController


  def index
    @reviews = Review.all
  end

  def new
    @review = Review.new
  end

  def create
    @toilet = Toilet.find(params[:toilet_id])
    @review = Review.new(review_params)
    @review.toilet = @toilet

    @review.save

    redirect_to toilet_path(@toilet)
  end

  def edit
  end

  def show
  end

  def update
    @review.update(review_params)
    @review.toilet = @toilet
    redirect_to toilet_path(@toilet)
  end

  def destroy
    @review.destroy
    redirect_to toilet_path(@review.toilet)
  end

  private
  def review_params
    params.require(:review).permit(:description, :rating)
  end

  def find_review
    @review = Review.find(params[:id])
  end
end

app/controllers/toilets_controller.rb
class ToiletsController < ApplicationController
  before_action :find_toilet, only: %i[edit show update destroy]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    if params[:query].present?
      sql_query = " \
        toilets.name ILIKE :query \
        OR toilets.location ILIKE :query \
        "
      @toilets = Toilet.where(sql_query, query: "%#{params[:query]}%")
    else
      @toilets = Toilet.all.order("created_at desc")
    end

    @markers = @toilets.geocoded.map do |toilet|
      {
        lat: toilet.latitude,
        lng: toilet.longitude,
        info_window: render_to_string(partial: "info_window", locals: { toilet: toilet })
      }
    end
  end

  def new
    @toilet = Toilet.new
  end

  def create
    @toilet = Toilet.new(toilet_params)
    @toilet.user = current_user
    if @toilet.save
      redirect_to toilet_path(@toilet)
    else
      render :new
    end
  end

  def edit
  end

  def show
  end

  def update
    @toilet.update(toilet_params)
    redirect_to toilet_path(@toilet)
  end

  def destroy
    @toilet.destroy

    # no need for app/views/restaurants/destroy.html.erb
    redirect_to root_path
  end

  private

  def toilet_params
    params.require(:toilet).permit(:location, :category, :price, :name, :description, :photo, :gender)
  end

  def find_toilet
    @toilet = Toilet.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<<div class="log">
<h1>Edit your booking</h1>
<%= simple_form_for([@booking]) do |f| %>
  <%= f.input :start_date, as: :select, collection: [['Asap (5min)!', Time.now + 5.minutes], ['I can hold it for 15 min', Time.now + 15.minutes] ,['I can hold it for 30 min', Time.now + 30.minutes]], prompt: '- Are you in a hurry?', label: false %>
  <div class="form-actions btn btn-ghost">
    <%= f.submit "Update your booking", class: "btn btn-primary" %>
  </div>
<% end %>
</div>

app/views/bookings/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://d18lkz4dllo6v2.cloudfront.net/cumulus_uploads/entry/2018-08-16/Urinals.jpg?pw=1200);">
    <div class="mega">
      <% if user_signed_in? %>
        <h1>Your<strong> Reservations</strong> !</h1>
        <h2>You can see here all your reservations</h2>
      <% else %>
        <h1>Your<strong> Reservations</strong> !</h1>
        <a class="btn btn-gradient" href="/users/sign_up">Create your account now 💦 </a>
      <% end %>
    </div>
</div>

<% if user_signed_in? %>
  <% if @bookings.present? %>
    <div class="container">
      <div class="cards">
          <% @bookings.each do |booking| %>
            <div class="card-product">
              <% if booking.toilet.photo.attached? %>
                <%= cl_image_tag booking.toilet.photo.key, height: 300, width: 400, crop: :fill %>
              <% else %>
                <%= image_tag(image_path("https://res.cloudinary.com/dlyi5kech/image/upload/v1653648388/development/WC_jo2l1c.jpg"), height: 300, width: 400, crop: :fill) %>
              <% end %>
              <div class="card-product-infos">
                <h2><%=booking.toilet.name%></h2>
                <p><%=booking.toilet.location%></p>
                <strong><%=booking.toilet.price%> Euros</strong> </p>
                <p><%= link_to "Reservation infos", booking_path(booking), class: "btn small-btn-show btn-test" %></p>
                <p><%= link_to "Rebook this toilet", new_toilet_booking_path(booking.toilet), class: "btn small-btn-book btn-test"  %></p>
                <p><%= link_to "Cancel booking", booking_path(booking), method: :delete, class: "btn small-btn-delete btn-test", data: {confirm: "Cancel booking ?"} %></p>
              </div>
            </div>
          <% end %>
      </div>
    </div>
  <% else %>
  <div class="no-booking">
  <br>
    It seems you haven't booked any PISSR Toilet yet !
  <div>
  <br>
  <% end %>
  <p><%= link_to "Go back to find a toilet ", toilets_path, class: "btn btn-book" %></p>
<% else %>
<% end %>

app/views/bookings/new.html.erb
<div class="container_show_seb">
  <div class="card-trip-seb">
      <% if @toilet.photo.attached? %>
        <%= image_tag(@toilet.photo) %>
      <% else%>
        <%= image_tag(image_path("https://res.cloudinary.com/dlyi5kech/image/upload/v1653648388/development/WC_jo2l1c.jpg")) %>
      <% end %>
    <div class="card-trip-infos-seb">
      <div>
        <h2>More info about <%=@toilet.name%>:</h2>
        <p><%=@toilet.description%></p>
        <br>
        <p>Average rating for this toilet: <strong><%= @toilet.reviews.average(:rating).to_f %></strong></p>
        <p>Where? <h2></h2><%=@toilet.location%></h2></p>
      </div>
      <h2 class="card-trip-pricing-seb">Price per pee is <%=@toilet.price%>€</h2>
      <% if @toilet.photo.attached? %>
        <%= image_tag(@toilet.user.photo, class: "card-trip-user-seb avatar-bordered") %>
      <% else%>
        <%= image_tag("https://res.cloudinary.com/dlyi5kech/image/upload/v1653654146/Image_d_iOS_oqqiak.jpg", class: "card-trip-user-seb avatar-bordered") %>
      <% end %>
    </div>
  </div>
  <div class="card-trip-seb">
    <div class="log">
      <H3>Book <%=@toilet.name%>'s toilet now!</H3>
      <%= simple_form_for [@toilet, @booking] do |f| %>
      <br>
      <h2>When do you want to pee?</h2>
      <%= f.input :start_date, as: :select, collection: [['Asap (5min)!', Time.now + 5.minutes], ['I can hold it for 15 min', Time.now + 15.minutes] ,['I can hold it for 30 min', Time.now + 30.minutes]], prompt: '- Are you in a hurry?', label: false %>
      <div id="wraper">
        <%= f.submit "Book #{@toilet.name}", class: "btn btn-primary" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container_show">
  <br>
  <% booking = Booking.find(params[:id]) %>
  <% if (((booking.start_date - Time.now)/60).to_i).positive? %>
    <h1>Enjoy your pee in <%= ((booking.start_date - Time.now)/60).to_i %> min 😎</h1>
    <div class="card-trip-seb">
        <% if booking.toilet.photo.attached? %>
          <%= image_tag(booking.toilet.photo) %>
        <% else%>
          <%= image_tag(image_path("https://res.cloudinary.com/dlyi5kech/image/upload/v1653648388/development/WC_jo2l1c.jpg")) %>
        <% end %>
      <div class="card-trip-infos-seb">
        <div>
          <h4>Your booked toilet: <%=booking.toilet.name%></h4>
          <h2>More info about <%=booking.toilet.name%></h2>
          <p><%=booking.toilet.description%></p>
          <br>
          <h4>Location</h4>
          <h4><%=booking.toilet.location%></h4>
          <p><%= link_to "Edit booking", edit_booking_path(booking), class: "btn small-btn-show btn-test btn-book-reservation"  %></p>
          <p><%= link_to "Cancel booking", booking_path(booking), method: :delete, class: "btn small-btn-delete btn-test btn-cancel-reservation", data: {confirm: "Cancel booking ?"} %></p>
        </div>
        <% if booking.toilet.photo.attached? %>
          <%= image_tag(booking.user.photo, class: "card-trip-user-seb avatar-bordered") %>
        <% else%>
          <%= image_tag("https://res.cloudinary.com/dlyi5kech/image/upload/v1653654146/Image_d_iOS_oqqiak.jpg", class: "card-trip-user-seb avatar-bordered") %>
        <% end %>
      </div>
      <h4 class="card-trip-pricing">Price per pee is <%=booking.toilet.price%>€</h4>
    </div>
  <% else %>
    <h1>Did you enjoy your pee?</h1>
    <div class="card-trip-seb">
      <%= image_tag("https://res.cloudinary.com/dlyi5kech/image/upload/v1653657539/chat_potte_fjmqq4.jpg") %>
    </div>
    <div class="container_https://res.cloudinary.com/dlyi5kech/image/upload/v1653648388/development/WC_jo2l1c.jpg">
      <%= link_to "Make a toilet review", new_toilet_review_path(booking.toilet), class: "form-actions btn btn-ghost" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pissr | People In Search of Safe Restroom</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>
  <body>
  <%= render 'shared/navbar' %>
  <%= render 'shared/flashes' %>
  <%= yield %>
  <%= render 'shared/footer' %>
  </body>
</html>

app/views/reviews/new.html.erb
<div class="log">
  <h1>Happy for your pee? Let a review!</h1>
  <%= simple_form_for([@toilet, @review], url: toilet_reviews_path, method: :post) do |f|%>
    <%= f.input :description %>
    <%= f.input :rating %>
  <div class="log_btn">
    <div class="form-actions btn btn-ghost">
      <%= f.button :submit, "Send my review"%>
      <% end %>
    </div>
  </div>
 </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<%# FOOTER %>
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/sebd141/pisseur"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This website has been made with <i class="fas fa-heart"></i> by Antoine, Sébastien, Val and Archi
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/#", class: "navbar-brand" do %>
     <%= image_tag("pissr_logo.png", size: "70x50") %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <%# <li class="nav-item">
            <%# <%= link_to "Messages", "#", class: "nav-link" %>
          <%# </li>  %>
          <li class="nav-item dropdown">
            <%= cl_image_tag current_user.photo.key, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Add a place to pee",  new_toilet_path, class: "dropdown-item" %>
              <%= link_to "My reservations", bookings_path, class: "dropdown-item" %>
              <%# <%= link_to "Places where I peed",  "", class: "dropdown-item" %> 
              <%= link_to "Edit my profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
              <%= link_to "Become a Pissr",  new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/toilets/_info_window.html.erb
<h2><%= toilet.name %></h2>
<p><%= toilet.location %></p>

app/views/toilets/edit.html.erb
<div class="log">
<h1>Edit your toilet</h1>
<%= simple_form_for([@user, @toilet]) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :location %>
  <%= f.input :price %>
  <%= f.input :category, collection: ['urinal', 'washing toilet', 'Turkish toilet', 'dry toilet', 'chemical toilet'], prompt: "- What type of toilet?" %>
  <%= f.input :photo, as: :file %>

  <%= f.input :gender, collection: ['male', 'female', 'non-binary'], prompt: "- Select gender preferance(s)"  %>
  <div class="form-actions btn btn-ghost">
    <%= f.button :submit, "Update your toilet" %>
  </div>
<% end %>
</div>

app/views/toilets/index.html.erb
<%# BANNER %>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://d18lkz4dllo6v2.cloudfront.net/cumulus_uploads/entry/2018-08-16/Urinals.jpg?pw=1200);">
  <div class="mega">
    <h1>People In <strong>Search</strong> of <strong>Safe Restroom</strong>!</h1>
    <p>Change your life and find where to pee fast.</p>
    <% if user_signed_in? %>
      <h1>Find your favorite pee spot</h1>
    <% else %>
      <a class="btn btn-gradient" href="/users/sign_up">Create your account now 💦 </a>
    <% end %>
  </div>
</div>

<div class="search">
  <div class="search-form-control">
    <%= form_tag toilets_path, method: :get do %>
      <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Find a toilet"
      %>
      <%= submit_tag "Search", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<div class="container">
  <div class="map_seb"
       data-controller="mapbox"
       data-mapbox-markers-value="<%= @markers.to_json %>"
       data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
  <div class="cards">
    <% @toilets.each do |toilet| %>
      <div class="card-product">
        <% if toilet.photo.attached? %>
          <%= cl_image_tag toilet.photo.key, height: 300, width: 400, crop: :fill %>
        <% else%>
          <%= image_tag(image_path "https://res.cloudinary.com/dlyi5kech/image/upload/v1653648388/development/WC_jo2l1c.jpg", height: 300, width: 400, crop: :fill) %>
        <% end %>

        <div class="card-product-infos">
          <h2><%=toilet.name%></h2>
          <p><%=toilet.location%></p>
          <strong><%=toilet.price%> Euros</strong> </p>
          <p><%= link_to "Show more", toilet_path(toilet), class: "btn small-btn-show btn-test" %></p>
          <p><%= link_to "Book #{toilet.name}", new_toilet_booking_path(toilet), class: "btn small-btn-book btn-test" %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/toilets/new.html.erb
<div class="log">
<h1>NEW PISSR TOILET</h1>
<%= simple_form_for([@user, @toilet]) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :location %>
  <%= f.input :price %>
  <%= f.input :category, collection: ['urinal', 'washing toilet', 'Turkish toilet', 'dry toilet', 'chemical toilet'], prompt: "- What type of toilet?" %>
  <%= f.input :photo, as: :file %>
  <%= f.input :gender, collection: ['male', 'female', 'non-binary'], prompt: "- Select gender preferance(s)" %>
  <div class="form-actions btn btn-ghost">
          <%= f.button :submit, "CREATE A PISSR TOILET" %>
    </div>
  </div>
<% end %>
</div>

app/views/toilets/show.html.erb
<%# CARD TRIP %>
<div class="container_show">
  <div class="card-trip">
      <% if @toilet.photo.attached? %>
        <%= image_tag(@toilet.photo) %>
      <% else%>
        <%= image_tag(image_path("https://res.cloudinary.com/dlyi5kech/image/upload/v1653648388/development/WC_jo2l1c.jpg")) %>
      <% end %>
    <div class="card-trip-infos">
      <div>
        <h2><%=@toilet.name%></h2>
        <p><%=@toilet.description%></p>
        <p><%=@toilet.location%></p>
        <br>
        <p>Average rating for this toilet: <strong><%= @toilet.reviews.average(:rating).to_f %></strong></p>
        <p>
      </div>
      <h2 class="card-trip-pricing">€<%=@toilet.price%></h2>
      <% if @toilet.photo.attached? %>
        <%= image_tag(@toilet.user.photo, class: "card-trip-user avatar-bordered") %>
      <% else%>
        <%= image_tag("https://res.cloudinary.com/dlyi5kech/image/upload/v1653654146/Image_d_iOS_oqqiak.jpg", class: "card-trip-user avatar-bordered") %>
      <% end %>
      <div class="btn-test">
        <%= link_to "Book a toilet", new_toilet_booking_path(@toilet), class: "form-actions btn btn-edit" %>
        <%= link_to "Edit toilet", edit_toilet_path(@toilet), class: "form-actions btn btn-edit" %>
        <%= link_to "Delete toilet", toilet_path(@toilet), method: :delete, class: "form-actions btn btn-delete", data: {confirm: "Delete this toilet ?" } %>
      </div>
    </div>
  </div>
</div>